images/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from .views import (ImageCreateView, ImageListView, ImageDetailView,
    ImageUpdateView, ImageDeleteView, GalleryCreateView, GalleryListView,
    GalleryDetailView, GalleryUpdateView, GalleryDeleteView, PieceCreateView,
    PieceListView, PieceDetailView, PieceUpdateView, PieceDeleteView,
    promote_gallery, promote_piece, ImageUserListView, GalleryUserListView,
    PieceUserListView, publish_image_view, publish_gallery_view,
    publish_piece_view,)

app_name = "images"

urlpatterns = [
    path(
        'upload/',
        ImageCreateView.as_view(),
        name='image_create'
    ),
    path(
        '',
        ImageListView.as_view(),
        name='image_list'
    ),
    
    path(
        '<int:pk>/',
        ImageDetailView.as_view(),
        name='image_detail'
    ),
    path(
        'modify/<int:pk>/',
        ImageUpdateView.as_view(),
        name='image_update'
    ),
    path('publish/<int:pk>/', publish_image_view, name='publish_image'),
    path('artwork/publish/<slug:slug>/', publish_piece_view, name='publish_piece'),
    path(
        'gallery/create/',
        GalleryCreateView.as_view(),
        name='gallery_create'
    ),
    path(
        'gallery/',
        GalleryListView.as_view(),
        name='gallery_list'
    ),
    path(
        'gallery/<slug:slug>/',
        GalleryDetailView.as_view(),
        name='gallery_detail'
    ),
    path(
        'gallery/modify/<slug:slug>/',
        GalleryUpdateView.as_view(),
        name='gallery_update'
    ),
    path(
        'gallery/delete/<int:pk>/',
        GalleryDeleteView.as_view(),
        name='gallery_delete'
    ),
    path(
        'gallery/promote/<int:pk>/',
        promote_gallery,
        name='promote_gallery'
    ),
    path('gallery/publish/<slug:slug>/', publish_gallery_view, name='publish_gallery'),
    path(
        'artworks/add/',
        PieceCreateView.as_view(),
        name='piece_create'
    ),
    path(
        'artworks/modify/<slug:slug>/',
        PieceUpdateView.as_view(),
        name='piece_update'
    ),
    path(
        'artworks/',
        PieceListView.as_view(),
        name='piece_list'
    ),
    path(
        'artworks/<slug:slug>/',
        PieceDetailView.as_view(),
        name='piece_detail'
    ),
    path(
        'artworks/delete/<int:pk>/',
        PieceDeleteView.as_view(),
        name='piece_delete'
    ),
    path(
        'artworks/promote/<int:pk>/',
        promote_piece,
        name='promote_piece'
    ),
    path(
        'member/<slug:user>/',
        ImageUserListView.as_view(),
        name='image_user_list'
    ),
    path(
        'gallery/member/<slug:user>/',
        GalleryUserListView.as_view(),
        name='gallery_user_list'
    ),
    path(
        'artworks/member/<slug:user>/',
        PieceUserListView.as_view(),
        name='piece_user_list'
    ),
]

people/urls.py
from django.urls import path
from people.views import (ArtistCreateView, ArtistListView, ArtistDetailView,
    ArtistUpdateView, ArtistDeleteView, ArtistUserListView, publish_artist_view, 
    promote_artist)

app_name = "people"

urlpatterns = [
    path('artists/new/', ArtistCreateView.as_view(), name="artist_create"),
    path('artists/modify/<slug:slug>/', ArtistUpdateView.as_view(), name="artist_update"),
    path('artists/delete/<int:pk>/', ArtistDeleteView.as_view(), name="artist_delete"),
    path('artists/publish/<slug:slug>/', publish_artist_view, name="artist_publish"),
    path('artists/promote/<int:pk>/', promote_artist, name="artist_promote"),
    path('artists/member/<slug:user>/', ArtistUserListView.as_view(), name="artist_user_list"),
    path('artists/<slug:slug>/', ArtistDetailView.as_view(), name="artist_detail"),
    path('artists/', ArtistListView.as_view(), name="artist_list"),
]

tags/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from tags.views import TagCreateView

app_name = "tags"

urlpatterns = [
    path('new/', TagCreateView.as_view(), name='new'),
]

images/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin,
    )
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic.edit import CreateView, FormView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.core.files.images import ImageFile
from accounts.mixins import UserObjectProtectionMixin
from accounts.models import User, Member
from .forms import ImageCreateForm, ImageUpdateForm, GalleryForm, PieceForm
from .models import Image, Gallery, Piece

# Create your views here.

class ImageCreateView(LoginRequiredMixin, CreateView):

    model = Image
    form_class = ImageCreateForm
    template_name_suffix = '_create_form'

    def form_valid(self, form):
        form.instance.creation_date = timezone.now()
        form.instance.user = self.request.user
        return super().form_valid(form)
	
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        else:
            return reverse('images:image_detail', kwargs={'pk': self.object.pk})

class ImageListView(ListView):

    model = Image
    paginate_by = 30
    queryset = Image.objects.filter(is_public=True)
    ordering = ['-weight', '-creation_date']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class ImageUserListView(ListView):

    model = Image
    paginate_by = 30 
    ordering = ['is_public', '-creation_date']

    def get_queryset(self, *args, **kwargs):
        target = User.objects.get(username=self.kwargs['user'])
        return Image.objects.filter(user=target)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        target = User.objects.get(username=self.kwargs['user'])
        context['user_only'] = True
        context['target'] = target 
        return context

class ImageDetailView(DetailView):

    model = Image

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Tell the template whether or not to render the marshmallow
        u = self.request.user
        if u.is_authenticated:
            # get the users Member function
            m = get_object_or_404(Member, pk=u.pk)
            context['can_allocate'] = m.check_can_allocate_weight
        else:
            context['can_allocate'] = False
        return context

class ImageUpdateView(LoginRequiredMixin, UserObjectProtectionMixin, UpdateView):

    model = Image
    form_class = ImageUpdateForm
    template_name_suffix = '_update_form'
	
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
		
class ImageDeleteView(LoginRequiredMixin, UserObjectProtectionMixin, DeleteView):

    model = Image
    success_url = reverse_lazy('images:image_list')
	
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class GalleryCreateView(LoginRequiredMixin, CreateView):

    model = Gallery
    form_class = GalleryForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        elif 'slug' in self.kwargs:
            slug = self.kwargs['slug']
            return reverse('images:gallery_detail', kwargs={'slug': slug})
        else:
            return reverse('studio')	

    def get_form_kwargs(self):
        kwargs = super(GalleryCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class GalleryListView(ListView):

    paginate_by = 16 
    queryset = Gallery.objects.filter(is_public=True)
    ordering = ['-weight', '-creation_date']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class GalleryUserListView(LoginRequiredMixin, ListView):

    paginate_by = 16
    ordering = ['-weight', '-creation_date']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_only'] = True
        return context

    def get_queryset(self):
        return Gallery.objects.filter(user=self.request.user)

class GalleryDetailView(DetailView):

    model = Gallery

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Tell the template whether or not to render the marshmallow
        u = self.request.user
        if u.is_authenticated:
            # get the users Member function
            m = get_object_or_404(Member, pk=u.pk)
            context['can_allocate'] = m.check_can_allocate_weight
        else:
            context['can_allocate'] = False
        return context

class GalleryUpdateView(LoginRequiredMixin, UserObjectProtectionMixin, UpdateView):

    model = Gallery
    form_class = GalleryForm
	
    def get_success_url(self):
        # return the slug with the success url
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            return reverse_lazy('images:gallery_list')
        return reverse_lazy('images:gallery_detail', kwargs={'slug': slug})

    def get_form_kwargs(self):
        kwargs = super(GalleryUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class GalleryDeleteView(LoginRequiredMixin, UserObjectProtectionMixin, DeleteView):

    model = Gallery
	
    def get_success_url(self):
        return reverse_lazy('images:gallery_list')
      
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class PieceCreateView(LoginRequiredMixin, CreateView):

    model = Piece
    form_class = PieceForm
 
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        else:
            if 'slug' in self.kwargs:
                slug = self.kwargs['slug']
            else:
                return reverse('images:piece_list')
            return reverse('images:piece_detail', kwargs={'slug': slug})

    def get_form_kwargs(self):
        kwargs = super(PieceCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class PieceListView(ListView):

    paginate_by = 30
    queryset = Piece.objects.filter(is_public=True)
    ordering = ['-weight', '-creation_date']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class PieceUserListView(LoginRequiredMixin, ListView):

    paginate_by = 30

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_only'] = True
        return context

    def get_queryset(self):
        return Piece.objects.filter(
            user=self.request.user
        ).order_by('is_public', '-creation_date')

class PieceDetailView(DetailView):

    model = Piece

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Tell the template whether or not to render the marshmallow
        u = self.request.user
        if u.is_authenticated:
            # get the users Member function
            m = get_object_or_404(Member, pk=u.pk)
            context['can_allocate'] = m.check_can_allocate_weight
        else:
            context['can_allocate'] = False
        return context

class PieceUpdateView(LoginRequiredMixin, UserObjectProtectionMixin, UpdateView):

    model = Piece
    form_class = PieceForm
	
    def get_success_url(self):
        # return the slug with the success url
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            return reverse('images:pieces_list')
        return reverse('images:piece_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
		
    def get_form_kwargs(self):
        kwargs = super(PieceUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class PieceDeleteView(LoginRequiredMixin, UserObjectProtectionMixin, DeleteView):

    model = Piece
	
    def get_success_url(self):
        return reverse_lazy('studio')
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

def publish_image_view(request, pk):
    user = request.user
    instance = get_object_or_404(Image, pk=pk)
    successful = instance.publish(instance, user)
    if successful:
        messages.add_message(
            request,
            messages.INFO,
            '{} has been published'.format(
                instance,
            )
        )
    else:
        messages.add_message(
            request,
            messages.ERROR,
            '{} could not be published'.format(
                instance,
            )
        )
    return HttpResponseRedirect(
        reverse(
            'images:image_detail',
            kwargs={'pk': instance.pk}

images/templates/images/gallery_create_button_bar.html
<div class="row">
  <div class="col-2">
    <h5 class="form-label">New: </h5>
  </div>
  <div class="col-sm">
    <a class="btn-sm btn-primary" href="{% url 'images:image_create' %}?next={{ request.path }}">Image</a>
    <a class="btn-sm btn-primary" href="{% url 'images:piece_create' %}?next={{ request.path }}">Piece</a> 
    <a class="btn-sm btn-primary" href="{% url 'tags:new' %}?next={{ request.path }}">Tag</a>
  </div>
</div>
<br>
<br>

images/templates/images/gallery_detail_button_bar.html
<div class="row">
  <div class="col">
    <a href="{% url 'images:gallery_delete' object.pk %}">
      <button type="button" class="btn btn-danger float-right">Delete</button>
    </a>
    <a href="{% url 'images:gallery_update' object.slug %}">
      <button type="button" class="btn btn-warning float-right">Edit</button>
    </a>
  </div>
</div>

images/templates/images/gallery_list_button_bar.html
<div class="row">
  <div class="col">
    <h3 class="images-gallery-title">
      {% if user_only %}
        {% if user.first_name and user.last_name %}
          {{ user.first_name }} {{ user.last_name }}{% else %}{{ user }}{% endif %}'s Galleries
      {% else %}
        Galleries
      {% endif %}
    </h3>
  </div>
  {% if request.user.is_authenticated %}
    <div class="col-">
      <div class="container">
        <a href="{% url 'images:gallery_create' %}">
          <button type="button" class="btn btn-primary">New Gallery</button>
        </a>
      </div>
    </div>
  {% endif %}
</div>

images/templates/images/gallery_list_item.html
{% if gallery.is_public or update.user == request.user %}
  <li class="list-group-item images-gallery-li">
    <div class="row">
      <div class="col-sm">
        <img src="{{ gallery.cover_image.image_file.url }}" class="images-gallery-list-image float-left" alt="{{ gallery.images.first.title }}">
      </div>
      <div class="col-sm">
        <a href="{% url 'images:gallery_detail' gallery.slug %}">
          <h3 class="images-gallery-caption">{{ gallery.title }}</h3>
        </a>
        <p class="images-gallery-caption">{{ gallery.caption }}</p>
        <p class="images-gallery-credit clear">
        <i>curated by
          {% if gallery.user.first_name and gallery.user.last_name %}
            {{ gallery.user.first_name }} {{ gallery.user.last_name }}
          {% else %}
            {{ gallery.user }}
          {% endif %}
          {% if gallery.publication_date %}
            on {{ gallery.publication_date|date:"M d, Y" }}
          {% endif %}
          {% if gallery.location %}
            from {{ gallery.location }}
          {% endif %}</i></p>
        {% if not gallery.is_public %}
          <span class="badge badge-secondary">Unpublished</span>
        {% endif %}
        {% if user_only and gallery.user == request.user %}
          <a href="{% url 'images:gallery_update' gallery.slug %}?next={{ request.path }}">
            <button class="btn-sm btn-warning">Edit</button>
          </a>
        {% endif %}
        {% if not gallery.is_public %}
          <a href="{% url 'images:gallery_delete' gallery.pk %}?next={{ request.path }}">
            <button class="btn-sm btn-danger">Delete</button>
          </a>
        {% endif %}
      </div>
    </div> 
  </li>
{% endif %}

images/templates/images/gallery_update_form.html
{% extends 'base.html' %}
{% block body_block %}
  <div class ="container uniForm edit-bg">
    <div class="container">
      <h2 class="images-title">Gallery Modification Form</h2>
      <ul>
        <li>Slugs must be unique as they are used in the URL that will point to your new gallery.</li>
        <li>Tags and Images must be created in advance.</li>
        <li>To select multiple objects, click while pressing ctrl</li>
      </ul>
    </div>
    <br>
    <div class="container">
      <form  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Modify" class="btn btn-success">
      </form>
      <br>
      {% if not object.is_public %}
        <a href="{% url 'images:publish_gallery' object.slug %}">
          <button class="btn btn-success">Publish</button>
        </a>
      {% endif %}
      <br>
    </div>
  </div>
{% endblock %}

images/templates/images/image_confirm_delete.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container images-bg">
  <div class="container">
    <form method="post">{% csrf_token %}
      <p>Are you sure you want to delete the image object "{{ object }}"?</p>
      <input type="submit" value="Confirm" class="btn btn-danger">
    </form>
  </div>
  <br>
</div>
{% endblock %}

images/templates/images/image_create_form.html
{% extends 'base.html' %}
{% block body_block %}
<div class ="container uniForm create-bg">
    <div class="container">
      <h2 class="images-title">New Image Submission Form</h2>
    </div>
    <br>
    <div class="container">
      <form  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'form_fields.html' %}
        <input type="submit" value="Upload" class="btn btn-success">
      </form>
    </div>
    <br>
</div>
{% endblock %}

images/templates/images/piece_create_button_bar.html
<div class="row">
  <div class="col-2">
    <h5 class="form-label">New: </h5>
  </div>
  <div class="col-sm">
    <a class="btn-sm btn-primary" href="{% url 'images:image_create' %}?next={{ request.path }}">Image</a>
    <a class="btn-sm btn-primary" href="{% url 'people:artist_create' %}?next={{ request.path }}">Artist</a> 
    <a class="btn-sm btn-primary" href="{% url 'tags:new' %}?next={{ request.path }}">Tag</a>
  </div>
</div>
<br>
<br>

images/templates/images/piece_form.html
{% extends 'base.html' %}
{% block body_block %}
{% load crispy_forms_tags %}
<div class ="container create-bg">
    <div class="container">
      <h2 class="images-title">New Piece Submission Form</h2>
      <p>
        Pieces are single works of art that are exhibited in a Gallery. Each piece has one uploaded Image along with information about the artists, medium, contacts, links and price. Pieces are also ordered. Pieces with lower numbers will appear first in the Gallery views. If two or more Pieces have the same number, the Piece that was added first will appear before the others. If the Image, Artists or Tags you would like to include have already been added, select select them from the menus below. Otherwise, you can add them on the fly by pressing one of the buttons below. Please note: only the Administrator can add new types of currency.

      </p>
    </div>
    <div class="container">
      {% include './piece_form_button_bar.html' %}
    </div>
    <form  method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <!-- Custom model choice form field for Image -->
      <div class="row">
        <div class="col-sm-2">
          <h5 class="form-label">{{ form.image.label_tag }}</h5>
        </div>
        <div class="col-sm-10 images-form-selector">
          {{ form.image.errors }}
          <p>{{ form.image.help_text}}</p>
          {% if form.image.field.choices.queryset.all|length == 0 %}
            <p><i>You haven't uploaded any images yet.</i></p>
          {% else %}
            {% for value in form.image.field.choices %}
              {% if value|first != '' %}
                <div class="studio-images-card float-left" style="background-image:url('/media/{{ value.2.thumbnail_file }}')">
                  <p>&nbsp;<input type="radio" value="{{ value|first }}" name="headline_img" {% if object.image.pk == value|first %}checked{% endif %}></p>
                </div>
              {% endif %}
            {% endfor %}
          {% endif %}
        </div>
      </div>
      <br>
      <br>
      <!-- Custom multiple model choice form field for Detail Images -->
      <div class="row">
        <div class="col-sm-2">
          <h5 class="form-label">{{ form.detail_images.label_tag }}</h5>
        </div>
        <div class="col-sm-10 images-form-selector">
          {{ form.detail_images.errors }}
          <p>{{ form.detail_images.help_text}}</p>
          {% if form.detail_images.field.choices.queryset.all|length == 0 %}
            <p><i>You haven't published any images yet.</i></p>
          {% else %}
            {% for value, label, obj in form.detail_images.field.choices %}
              {% if value != '' %}
                <div class="studio-images-card float-left" style="background-image:url('/media/{{ obj.thumbnail_file }}')">
                  <p>&nbsp;<input type="checkbox" value="{{ value }}" name="detail_images" {% if obj in object.detail_images.all %}checked{% endif %}></p>
                </div>
              {% endif %}
            {% endfor %}
          {% endif %}
        </div>
      </div>
      <br>
      <br>
      <!-- Custom multiple model choice form field for Artists -->
      <div class="row">
        <div class="col-sm-2">
          <h5 class="form-label">{{ form.artists.label_tag }}</h5>
        </div>
        <div class="col-sm-10 images-form-selector">
          {{ form.artists.errors }}
          <p>{{ form.artists.help_text}}</p>
          {% if form.artists.field.choices.queryset.all|length == 0 %}
            <p><i>You haven't published any artist profiles yet.</i></p>
          {% else %}
            {% for value, label, obj in form.artists.field.choices %}
              {% if value != '' %}
                <div class="studio-images-card float-left" style="background-image:url('/media/{{ obj.image.thumbnail_file }}')">
                  <p>&nbsp;<input type="checkbox" value="{{ value }}" name="artists" {% if obj in object.artists.all %}checked{% endif %}></p>
                </div>
              {% endif %}
            {% endfor %}
          {% endif %}
        </div>
      </div>
      <br>
      <br>
      <!-- Standard field iterator -->
      {% for field in form %}
        {% if field != form.image and field != form.detail_images  and field != form.artists %}
          {{ field.errors }}
          <div class="row">
            <div class="col-sm-2">
              <h5 class="form-label">{{ field.label_tag }}</h5>
            </div>
            <div class="col-sm-10">
              <p>{{ field.help_text }}</p>
              {{ field }}
            </div>
          </div>
          <br>
          <br>
        {% endif %}
      {% endfor %}
      <input type="submit" value="Upload" class="btn btn-success">
    </form>
    <br>
    <br>
</div>
{% endblock %}

images/templates/images/piece_form_button_bar.html
<div class="row">
  <div class="col-2">
    <h5 class="form-label">New: </h5>
  </div>
  <div class="col-sm">
    <a class="btn-sm btn-primary" href="{% url 'images:image_create' %}?next={{ request.path }}">Image</a>
    <a class="btn-sm btn-primary" href="{% url 'people:artist_create' %}?next={{ request.path }}">Artist</a> 
    <a class="btn-sm btn-primary" href="{% url 'tags:new' %}?next={{ request.path }}">Tag</a>
  </div>
</div>
<br>
<br>

images/templates/images/piece_form_fields.html
{% for field in form %}
  {{ field.errors }}
  <div class="row">
    <div class="col-2">
      <h5 class="form-label">{{ field.label_tag }}</h5>
    </div>
    <div class="col-sm-10">
      {{ field }}
    </div>
  </div>
  <br>
  <br>
{% endfor %}

images/templates/images/piece_image.html
<div class="container">
  <a href="{% url 'images:image_detail' object.featured_img.pk %}">
    <img class="updates-featured-image" src="/media/{{ object.featured_img.image_file }}" alt="{{ object.featured_img.caption }}">
  </a>
  <p class="updates-featured-image-credit"><i>{{ object.featured_img.credit }}</i></p>
</div>

images/templates/images/piece_list_card.html
<a href="{% url 'images:piece_detail' piece.slug %}">
  <div class="float-left images-piece-card" style="background-image:url('/media/{{ piece.image.thumbnail_file }}">
    <span class="images-piece-card-title">{{ piece.image.title }}</span>
      {% if not piece.is_public %}
        <span class="badge badge-secondary">Unpublished</span>
      {% endif %}
  </div>
</a>

images/templates/images/piece_update_form.html
{% extends 'base.html' %}
{% block body_block %}
<div class ="container edit-bg">
  <div class="container">
    <h2 class="updates-title">Piece Modification Form</h2>
    <br>
    <form  method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% include 'form_fields.html' %}
      <input type="submit" value="Modify" class="btn btn-success">
    </form>
    <br>
    {% if not object.is_public %}
      <a href="{% url 'images:publish_piece' object.slug %}">
        <button class="btn btn-success">Publish</button>
      </a>
    {% endif %}
    <br>
  </div>
</div>
{% endblock %}