images/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from .views import (ImageCreateView, ImageListView, ImageDetailView,
    ImageUpdateView, ImageDeleteView, GalleryCreateView, GalleryListView,
    GalleryDetailView, GalleryUpdateView, GalleryDeleteView, PieceCreateView,
    PieceListView, PieceDetailView, PieceUpdateView, PieceDeleteView,
    promote_gallery, promote_piece, ImageUserListView, GalleryUserListView,
    PieceUserListView, publish_image_view, publish_gallery_view,
    publish_piece_view,)

app_name = "images"

urlpatterns = [
    path(
        'upload/',
        ImageCreateView.as_view(),
        name='image_create'
    ),
    path(
        '',
        ImageListView.as_view(),
        name='image_list'
    ),
    
    path(
        '<int:pk>/',
        ImageDetailView.as_view(),
        name='image_detail'
    ),
    path(
        'modify/<int:pk>/',
        ImageUpdateView.as_view(),
        name='image_update'
    ),
    path('publish/<int:pk>/', publish_image_view, name='publish_image'),
    path('artwork/publish/<slug:slug>/', publish_piece_view, name='publish_piece'),
    path(
        'gallery/create/',
        GalleryCreateView.as_view(),
        name='gallery_create'
    ),
    path(
        'gallery/',
        GalleryListView.as_view(),
        name='gallery_list'
    ),
    path(
        'gallery/<slug:slug>/',
        GalleryDetailView.as_view(),
        name='gallery_detail'
    ),
    path(
        'gallery/modify/<slug:slug>/',
        GalleryUpdateView.as_view(),
        name='gallery_update'
    ),
    path(
        'gallery/delete/<int:pk>/',
        GalleryDeleteView.as_view(),
        name='gallery_delete'
    ),
    path(
        'gallery/promote/<int:pk>/',
        promote_gallery,
        name='promote_gallery'
    ),
    path('gallery/publish/<slug:slug>/', publish_gallery_view, name='publish_gallery'),
    path(
        'artworks/add/',
        PieceCreateView.as_view(),
        name='piece_create'
    ),
    path(
        'artworks/modify/<slug:slug>/',
        PieceUpdateView.as_view(),
        name='piece_update'
    ),
    path(
        'artworks/',
        PieceListView.as_view(),
        name='piece_list'
    ),
    path(
        'artworks/<slug:slug>/',
        PieceDetailView.as_view(),
        name='piece_detail'
    ),
    path(
        'artworks/delete/<int:pk>/',
        PieceDeleteView.as_view(),
        name='piece_delete'
    ),
    path(
        'artworks/promote/<int:pk>/',
        promote_piece,
        name='promote_piece'
    ),
    path(
        'member/<slug:user>/',
        ImageUserListView.as_view(),
        name='image_user_list'
    ),
    path(
        'gallery/member/<slug:user>/',
        GalleryUserListView.as_view(),
        name='gallery_user_list'
    ),
    path(
        'artworks/member/<slug:user>/',
        PieceUserListView.as_view(),
        name='piece_user_list'
    ),
]

links/urls.py
from django.urls import path
from .views import (LinkCreateView, LinkListView, LinkDetailView,
    LinkUpdateView, LinkDeleteView, LinkUserListView, promote_link,
    publish_link_view)

app_name = "links"

urlpatterns = [
    path('add/', LinkCreateView.as_view(), name='link_create'),
    path('', LinkListView.as_view(), name='link_list'),
    path('<int:pk>/', LinkDetailView.as_view(), name='link_detail'),
    path('modify/<int:pk>/', LinkUpdateView.as_view(), name='link_update'),
    path('delete/<int:pk>/', LinkDeleteView.as_view(), name='link_delete'),
    path('promote/<int:pk>/', promote_link, name='promote'),
    path('publish/<int:pk>/', publish_link_view, name='publish_link'),
    path('member/<slug:user>/', LinkUserListView.as_view(), name='link_user_list')
]
 

people/urls.py
from django.urls import path
from people.views import (ArtistCreateView, ArtistListView, ArtistDetailView,
    ArtistUpdateView, ArtistDeleteView, ArtistUserListView, publish_artist_view, 
    promote_artist)

app_name = "people"

urlpatterns = [
    path('artists/new/', ArtistCreateView.as_view(), name="artist_create"),
    path('artists/modify/<slug:slug>/', ArtistUpdateView.as_view(), name="artist_update"),
    path('artists/delete/<int:pk>/', ArtistDeleteView.as_view(), name="artist_delete"),
    path('artists/publish/<slug:slug>/', publish_artist_view, name="artist_publish"),
    path('artists/promote/<int:pk>/', promote_artist, name="artist_promote"),
    path('artists/member/<slug:user>/', ArtistUserListView.as_view(), name="artist_user_list"),
    path('artists/<slug:slug>/', ArtistDetailView.as_view(), name="artist_detail"),
    path('artists/', ArtistListView.as_view(), name="artist_list"),
]

tags/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from tags.views import TagCreateView

app_name = "tags"

urlpatterns = [
    path('new/', TagCreateView.as_view(), name='new'),
]

updates/urls.py
#from django.contrib import admin
from django.urls import path
from .views import (
    UpdatesListView, UpdatesDetailView, UpdatesCreateView,
    UpdatesUpdateView, UpdatesDeleteView, promote_update,
    UpdatesUserListView, updates_publish_view,
)

app_name = 'updates'
urlpatterns = [
    path('', UpdatesListView.as_view(), name='update_list'),
    path('add/', UpdatesCreateView.as_view(), name='update_create'),
    path('modify/<slug:slug>/', UpdatesUpdateView.as_view(), name='update_update'),
    path('delete/<int:pk>/', UpdatesDeleteView.as_view(), name='update_delete'),
    path('promote/<int:pk>/', promote_update, name='promote'),
    path('publish/<int:pk>/', updates_publish_view, name='publish_update'),
    path('member/<slug:user>/', UpdatesUserListView.as_view(), name='update_user_list'),
    path('<slug:slug>/', UpdatesDetailView.as_view(), name='update_detail'),
]

people/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from accounts.models import Profile
from links.models import Link
from marshmallows.models import MarshmallowMixin
from tags.models import MetaDataMixin

# Create your models here.

# Base Model
class Person(MetaDataMixin, MarshmallowMixin):

    slug = models.SlugField(max_length=40, unique=True)
    name = models.CharField(max_length=24, unique=True,)
    home_town = models.CharField(max_length=24, blank=True, null=True,)
    image = models.ForeignKey('images.image', on_delete=models.CASCADE,)
    links = models.ManyToManyField(Link, blank=True,)
    profile = models.ForeignKey(
        'accounts.profile',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['weight', '-creation_date',]

# Person is-a
class Artist(Person):

    statement = models.TextField(max_length=1024, blank=True, null=True,)
    media = models.TextField(max_length=1024, blank=True, null=True,)

    class Meta:
        ordering = ['name', '-creation_date']

# Person has-a
class Quote(MetaDataMixin, MarshmallowMixin):

    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    text = models.TextField(max_length=1024)
    
    def __str__(self):
        return '"{}" - {}"'.format(text, person)

    class Meta:
        ordering = ['weight', '-creation_date']

people/forms.py
from django import forms
from django.forms.widgets import Textarea, RadioSelect, CheckboxInput
from images.models import Image
from links.models import Link
from .models import Artist

class CustomModelChoiceIterator(forms.models.ModelChoiceIterator):

    def choice(self, obj):
        return self.field.prepare_value(obj), self.field.label_from_instance(obj), obj

class CustomModelChoiceField(forms.models.ModelChoiceField):

    def _get_choices(self):
        if hasattr(self, '_choices'):
            return self._choices
        return CustomModelChoiceIterator(self)

    choices = property(_get_choices, forms.ChoiceField._set_choices)

class CustomModelMultipleChoiceField(forms.models.ModelMultipleChoiceField):

    def _get_choices(self):
        if hasattr(self, '_choices'):
            return self._choices
        return CustomModelChoiceIterator(self)

    choices = property(_get_choices, forms.MultipleChoiceField._set_choices)

class ArtistForm(forms.ModelForm):

    image = CustomModelChoiceField(
        queryset=Image.objects.all(),
        help_text=Artist._meta.get_field('image').help_text,
    )
    
    class Meta:
        model = Artist 

        fields = [
            'name',
            'slug',
            'home_town',
            'image',
            'links',
            'statement',
            'media',
        ]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(ArtistForm, self).__init__(*args, **kwargs)
        self.fields['image'].queryset = Image.objects.filter(
            user=user,
        ).order_by(
            '-creation_date',
        )
        self.fields['links'].queryset = Link.objects.filter(
            user=user,
        ).order_by(
            '-creation_date',
        )

people/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import(LoginRequiredMixin,
    PermissionRequiredMixin,)
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic.edit import CreateView, FormView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from accounts.mixins import UserObjectProtectionMixin
from accounts.models import Member
from .forms import ArtistForm
from .models import Artist

# Create your views here.

class ArtistCreateView(LoginRequiredMixin, CreateView):

    model = Artist
    form_class = ArtistForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        else:
            if 'slug' in self.kwargs:
                slug = self.kwargs['slug']
            else:
                return reverse('people:artist_list')
            return reverse_lazy('people:artist_detail', kwargs={'slug': slug})

    def get_form_kwargs(self):
        kwargs = super(ArtistCreateView, self).get_form_kwargs() 
        kwargs['user'] = self.request.user
        return kwargs

class ArtistListView(ListView):

    queryset = Artist.objects.filter(is_public=True)
    paginate_by = 16
    ordering = ['-weight', '-creation_date',]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class ArtistUserListView(ListView):

    model = Artist
    paginate_by = 16

    def get_queryset(self):
        return Artist.objects.filter(
            user=self.request.user
        ).order_by('is_public', '-creation_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_only'] = True
        return context

class ArtistDetailView(DetailView):

    model = Artist

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Tell the template whether or not to render the marshmallow
        u = self.request.user
        if u.is_authenticated:
            print("AUTH OK!")
            # get the users Member function
            m = get_object_or_404(Member, pk=u.pk)
            context['can_allocate'] = m.check_can_allocate_weight()
        else:
            context['can_allocate'] = False
        artist = Artist.objects.get(slug=self.object.slug)
        context['pieces'] = artist.piece_set.all()
        return context

class ArtistUpdateView(LoginRequiredMixin, UserObjectProtectionMixin, UpdateView):

    model = Artist
    form_class = ArtistForm

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        else:
            if 'slug' in self.kwargs:
                slug = self.kwargs['slug']
            else:
                return reverse('people:artist_list')
            return reverse_lazy('people:artist_detail', kwargs={'slug': slug})

    def get_form_kwargs(self):
        kwargs = super(ArtistUpdateView, self).get_form_kwargs() 
        kwargs['user'] = self.request.user
        return kwargs

class ArtistDeleteView(LoginRequiredMixin, UserObjectProtectionMixin, DeleteView):

    model = Artist

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_success_url(self):
        return reverse_lazy('people:artist_list')

def publish_artist_view(request, slug):
    user = request.user
    instance = get_object_or_404(Artist, slug=slug)
    successful = instance.publish(instance, user)
    if successful:
        messages.add_message(
            request,
            messages.INFO,
            '{} has been published'.format(
                instance,
            )
        )
    else:
        messages.add_message(
            request,
            messages.ERROR,
            '{} could not be published'.format(
                instance,
            )
        )
    return HttpResponseRedirect(
        reverse(
            'people:artist_detail',
            kwargs={'slug': instance.slug}
        )
    )

def promote_artist(request, pk):
    m = get_object_or_404(Member, pk=request.user.pk)
    o = get_object_or_404(Artist, pk=pk)
    successful, link, weight  = m.allocate_weight(o)
    if successful:
        messages.add_message(
            request, messages.INFO,
            'You gave a marshmallow to {} weighing {}'.format(
                link,
                round(weight, 2)
            )
       )
    else:
        messages.add_message(
            request,
            messages.ERROR,
            'You failed to give a marshmallow to {}'.format(link)
        )
    return HttpResponseRedirect(reverse('people:artist_list'))

people/templates/people/artist_confirm_delete.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container people-artist-bg">
  <div class="container">
    <form method="post">{% csrf_token %}
      <p>Are you sure you want to delete the artist "{{ object }}"?</p>
      <input type="submit" value="Confirm" class="btn btn-danger">
    </form>
  </div>
  <br>
</div>
{% endblock %}

people/templates/people/artist_create_button_bar.html
<div class="row">
  <div class="col-2">
    <h5 class="form-label">New: </h5>
  </div>
  <div class="col-sm">
    <a class="btn-sm btn-primary" href="{% url 'images:image_create' %}?next={{ request.path }}">Image</a>
    <a class="btn-sm btn-primary" href="{% url 'links:link_create' %}?next={{ request.path }}">Link</a> 
    <a class="btn-sm btn-primary" href="{% url 'tags:new' %}?next={{ request.path }}">Tag</a>
  </div>
</div>
<br>
<br>

people/templates/people/artist_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container people-artist-bg">
  {% include './artist_detail_button_bar.html' %}
  <h1 class="people-artist-title">{{ object.name }}</h1>
  <img src="{{ object.image.image_file.url }}" class="people-artist-image float-left" alt="{{ object.image.caption }}">
  <h4 class="people-artist-title">Artist Statement</h4>
  <p class="people-artist-caption">"{{ artist.statement }}"</p>
  <h4 class="people-artist-title">Media</h4>
  <p class="people-artist-caption">{{ artist.media }}</p>
  <h4 class="people-artist-title">Home Town</h4>
  <p class="people-artist-caption">{{ artist.home_town }}</p>
  <br>
  <div class="clear"></div>
  <!-- Artworks -->
  {% if pieces %}
    <h3 class="people-artist-title">Artworks</h3>
    {% for piece in pieces %}
      {% include './piece_list_card.html' %}
    {% endfor %}
    <div class="clear"></div>
  {% endif %}
  <!-- Links -->
  {% if links %}
    <h3 class="people-artist-title">Links</h3>
    <ul class="list-group">
    {% for link in object.links.all %}
      {% include './artist_link_list_item.html' %}
    {% endfor %}
    </ul>
  {% endif %}
  {% if can_allocate  %}
    <a href="{% url 'people:artist_promote' object.pk  %}">
      <button type="button" class="btn btn-default float-right">&#9829;</button>
    </a>
    <div class="clear"></div>
    <br>
  {% endif %}
</div>
{% endblock %}

people/templates/people/artist_detail_button_bar.html
{% if request.user == object.user %}
  <div class="row">
    <div class="col">
      <a href="{% url 'people:artist_delete' object.pk %}">
        <button type="button" class="btn btn-danger float-right">Delete</button>
      </a>
      <a href="{% url 'people:artist_update' object.slug %}">
        <button type="button" class="btn btn-warning float-right">Edit</button>
      </a>
    </div>
  </div>
{% endif %}

people/templates/people/artist_form.html
{% extends 'base.html' %}
{% block body_block %}
  <div class ="container create-bg">
    <div class="container">
      <h2 class="images-title">New Artist Submission Form</h2>
      <p>
        The Artist object stores basic pertinent information about an individual artist.  Artists have an Image and may also have Links. If the Image or Links you would like to include have already been uploaded, select select them from the menus below. Otherwise, you can add them on the fly by pressing one of the buttons below.
      </p>
    </div>
    <div class="container">
      {% include './artist_form_button_bar.html' %}
    </div>
    <br>
    <br>
    <div class="container">
      <form  method="post" enctype="multipart/form-data">
        {% csrf_token %}
      <!-- Custom model choice form field for Image -->
      <div class="row">
        <div class="col-2">
          <h5 class="form-label">{{ form.image.label_tag }}</h5>
        </div>
        <div class="col-sm-10 images-form-selector">
          {{ form.image.errors }}
          <p>{{ form.image.help_text}}</p>
          {% if form.image.field.choices.queryset.all|length == 0 %}
            <p><i>No objects found.</i></p>
          {% else %}
            <!-- image grid layout for model choices -->
            {% for value in form.image.field.choices %}
              {% if value|first != '' %}
                <div class="studio-images-card float-left" style="background-image:url('/media/{{ value.2.thumbnail_file }}')">
                  <p>&nbsp;<input type="radio" value="{{ value|first }}" name="image" {% if object.image.pk == value|first %}checked{% endif %}></p>
                </div>
              {% endif %}
            {% endfor %}
          {% endif %}
        </div>
      </div>
      <br>
      <br>
      <!-- Standard field iterator -->
      {% for field in form %}
        {% if field != form.image %}
          {{ field.errors }}
          <div class="row">
            <div class="col-2">
              <h5 class="form-label">{{ field.label_tag }}</h5>
            </div>
            <div class="col-sm-10">
              <p>{{ field.help_text }}</p>
              {{ field }}
            </div>
          </div>
          <br>
          <br>
        {% endif %}
      {% endfor %}
        <input type="submit" value="Submit" class="btn btn-success">
      </form>
      <br>
    </div>
  </div>
{% endblock %}

people/templates/people/artist_form_button_bar.html
<div class="row">
  <div class="col-2">
    <h5 class="form-label">New: </h5>
  </div>
  <div class="col-sm">
    <a class="btn-sm btn-primary" href="{% url 'images:image_create' %}?next={{ request.path }}">Image</a>
    <a class="btn-sm btn-primary" href="{% url 'links:link_create' %}?next={{ request.path }}">Link</a> 
    <a class="btn-sm btn-primary" href="{% url 'tags:new' %}?next={{ request.path }}">Tag</a>
  </div>
</div>
<br>
<br>

people/templates/people/artist_link_list_item.html
<li class="list-group-item links-list-li">
  <a href="{{ link.url }}" class="links-list-link">
    <h4 class="links-list-title">{{ link.title }}</h4>
  </a>
  <p class="links-list-description">{{ link.description }}</p>
  <p class="links-list-link clear">{{ link.url }}</p>
</li>

people/templates/people/artist_list.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container links-bg">
  {% include "./artist_list_button_bar.html" %}
  {% if object_list %}
    {% include "page_control.html" %}
    <ul class="list-group">
      {% for artist in object_list %}
        {% include "./artist_list_item.html" %}
      {% endfor %}
    </ul>
    {% include "page_control.html" %}
  {% else %}
    <p>No one has admitted to being an "artist" yet. Check back soon.</p>
  {% endif %}
</div>
{% endblock %}

people/templates/people/artist_list_button_bar.html
<div class="row">
  <div class="col">
    <h3 class="links-title">
      {% if user_only %}
        {% if user.first_name and user.last_name %}
          {{ user.first_name }} {{ user.last_name }}{% else %}{{ user }}{% endif %}'s Artists
      {% else %}
        Artist
      {% endif %}
    </h3>
  </div>
  {% if request.user.is_authenticated %}
    <div class="col-">
      <div class="container">
        <a href="{% url 'people:artist_create' %}">
          <button type="button" class="btn btn-primary float-right">New Artist</button>
        </a>
      </div>
    </div>
  {% endif %}
</div>

people/templates/people/artist_list_item.html
{% if artist.is_public or artist.user == request.user %}
  <li class="list-group-item people-artist-list-item">
    <div class="row">
      <div class="col-sm-3">
        <img src="{{ artist.image.thumbnail_file.url }}" class="people-artist-thumbnail" alt="{{ artist.image.caption }}">
      </div>
      <div class="col-lg">
        <a href="{% url 'people:artist_detail' artist.slug %}" class="">
          <h3 class="people-artist-caption">{{ artist.name }}</h3>
        </a>
        {% if not artist.is_public %}
          <span class="badge badge-secondary">Unpublished</span>
        {% endif %}
        {% if artist.statement %}
          <p class="people-artist-caption">"{{ artist.statement }}"</p>
        {% endif %}
        {% if user_only and artist.user == request.user %}
          <a href="{% url 'people:artist_update' artist.slug %}?next={{ request.path }}">
            <button class="btn-sm btn-warning">Edit</button>
          </a>
          {% if not artist.is_public %}
            <a href="{% url 'people:artist_delete' artist.pk %}?next={{ request.path }}">
              <button class="btn-sm btn-danger">Delete</button>
            </a>
          {% endif %}
        {% endif %}
      </div>
    </div>
  </li>
{% endif %}

people/templates/people/artist_update_form.html
{% extends 'base.html' %}
{% block body_block %}
  <div class ="container uniForm edit-bg">
    <div class="container">
      <h2 class="links-title">Artist Modification Form</h2>
    </div>
    <br>
    <div class="container">
      <form  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Modify" class="btn btn-success">
      </form>
      <br>
      {% if not object.is_public %}
        <a href="{% url 'people:artist_publish' object.slug %}">
          <button class="btn btn-success">Publish</button>
        </a>
      {% endif %}
    </div>
  </div>
{% endblock %}

people/templates/people/piece_list_card.html
<a href="{% url 'images:piece_detail' piece.slug %}">
  <div class="float-left images-piece-card" style="background-image:url('/media/{{ piece.image.thumbnail_file }}">
    <span class="images-piece-card-title">{{ piece.image.title }}</span>
  </div>
</a>

people/templates/people/piece_list_item.html
<li class="list-group-item updates-list-item">
  <a href="{% url 'updates:update_detail' update.slug  %}" class="links-list-link">
    <h4 class="updates-title">{{ update.title }}</h4>
  </a>
  <img src="{{ update.featured_img.thumbnail_file.url }}" class="updates-list-thumbnail float-left">
  <p class="updates-list-caption">{{ update.headline }}</p>
  <p class="updates-link clear">
    <i>contributed by
      {% if update.user.first_name and update.user.last_name %}
        {{ update.user.first_name }} {{ update.user.last_name }}
      {% else %}
        {{ update.user }}
      {% endif %}
      {% if update.publication_date %}
        on {{ update.publication_date|date:"M d, Y" }}
      {% endif %}
      {% if update.location %}
        from {{ update.location }}
      {% endif %}
    </i>
  </p>
</li>