images/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from .views import (ImageCreateView, ImageListView, ImageDetailView,
    ImageUpdateView, ImageDeleteView, GalleryCreateView, GalleryListView,
    GalleryDetailView, GalleryUpdateView, GalleryDeleteView, PieceCreateView,
    PieceListView, PieceDetailView, PieceUpdateView, PieceDeleteView,
    promote_gallery, promote_piece, ImageUserListView, GalleryUserListView,
    PieceUserListView, publish_image_view, publish_gallery_view,
    publish_piece_view,)

app_name = "images"

urlpatterns = [
    path(
        'upload/',
        ImageCreateView.as_view(),
        name='image_create'
    ),
    path(
        '',
        ImageListView.as_view(),
        name='image_list'
    ),
    
    path(
        '<int:pk>/',
        ImageDetailView.as_view(),
        name='image_detail'
    ),
    path(
        'modify/<int:pk>/',
        ImageUpdateView.as_view(),
        name='image_update'
    ),
    path('publish/<int:pk>/', publish_image_view, name='publish_image'),
    path('artwork/publish/<slug:slug>/', publish_piece_view, name='publish_piece'),
    path(
        'gallery/create/',
        GalleryCreateView.as_view(),
        name='gallery_create'
    ),
    path(
        'gallery/',
        GalleryListView.as_view(),
        name='gallery_list'
    ),
    path(
        'gallery/<slug:slug>/',
        GalleryDetailView.as_view(),
        name='gallery_detail'
    ),
    path(
        'gallery/modify/<slug:slug>/',
        GalleryUpdateView.as_view(),
        name='gallery_update'
    ),
    path(
        'gallery/delete/<int:pk>/',
        GalleryDeleteView.as_view(),
        name='gallery_delete'
    ),
    path(
        'gallery/promote/<int:pk>/',
        promote_gallery,
        name='promote_gallery'
    ),
    path('gallery/publish/<slug:slug>/', publish_gallery_view, name='publish_gallery'),
    path(
        'artworks/add/',
        PieceCreateView.as_view(),
        name='piece_create'
    ),
    path(
        'artworks/modify/<slug:slug>/',
        PieceUpdateView.as_view(),
        name='piece_update'
    ),
    path(
        'artworks/',
        PieceListView.as_view(),
        name='piece_list'
    ),
    path(
        'artworks/<slug:slug>/',
        PieceDetailView.as_view(),
        name='piece_detail'
    ),
    path(
        'artworks/delete/<int:pk>/',
        PieceDeleteView.as_view(),
        name='piece_delete'
    ),
    path(
        'artworks/promote/<int:pk>/',
        promote_piece,
        name='promote_piece'
    ),
    path(
        'member/<slug:user>/',
        ImageUserListView.as_view(),
        name='image_user_list'
    ),
    path(
        'gallery/member/<slug:user>/',
        GalleryUserListView.as_view(),
        name='gallery_user_list'
    ),
    path(
        'artworks/member/<slug:user>/',
        PieceUserListView.as_view(),
        name='piece_user_list'
    ),
]

people/urls.py
from django.urls import path
from people.views import (ArtistCreateView, ArtistListView, ArtistDetailView,
    ArtistUpdateView, ArtistDeleteView, ArtistUserListView, publish_artist_view, 
    promote_artist)

app_name = "people"

urlpatterns = [
    path('artists/new/', ArtistCreateView.as_view(), name="artist_create"),
    path('artists/modify/<slug:slug>/', ArtistUpdateView.as_view(), name="artist_update"),
    path('artists/delete/<int:pk>/', ArtistDeleteView.as_view(), name="artist_delete"),
    path('artists/publish/<slug:slug>/', publish_artist_view, name="artist_publish"),
    path('artists/promote/<int:pk>/', promote_artist, name="artist_promote"),
    path('artists/member/<slug:user>/', ArtistUserListView.as_view(), name="artist_user_list"),
    path('artists/<slug:slug>/', ArtistDetailView.as_view(), name="artist_detail"),
    path('artists/', ArtistListView.as_view(), name="artist_list"),
]

qndbacklog/urls.py
from django.urls import path
from .views import (ObjectiveCreateView, ObjectiveDetailView,
    CurrentObjectiveListView, ObjectiveUpdateView, ObjectiveDeleteView,
    complete_objective, commit_objective, pay_bounty,)

app_name = "backlog"

urlpatterns = [
    path('', CurrentObjectiveListView.as_view(), name='objective_list'),
    path('objective/new/', ObjectiveCreateView.as_view(), name='objective_create'),
    path('objective/update/<int:pk>', ObjectiveUpdateView.as_view(), name='objective_update'),
    path('objective/delete/<int:pk>', ObjectiveDeleteView.as_view(), name='objective_delete'),
    path('objective/<int:pk>/', ObjectiveDetailView.as_view(), name='objective_detail'),
    path('objective/complete/<int:pk>/', complete_objective, name='complete_objective'),
    path('objective/commit/<int:pk>/', commit_objective, name='commit_objective'),
    path('objective/claim/<int:pk>/', pay_bounty, name='pay_bounty'),
]

tags/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from tags.views import TagCreateView

app_name = "tags"

urlpatterns = [
    path('new/', TagCreateView.as_view(), name='new'),
]

updates/urls.py
#from django.contrib import admin
from django.urls import path
from .views import (
    UpdatesListView, UpdatesDetailView, UpdatesCreateView,
    UpdatesUpdateView, UpdatesDeleteView, promote_update,
    UpdatesUserListView, updates_publish_view,
)

app_name = 'updates'
urlpatterns = [
    path('', UpdatesListView.as_view(), name='update_list'),
    path('add/', UpdatesCreateView.as_view(), name='update_create'),
    path('modify/<slug:slug>/', UpdatesUpdateView.as_view(), name='update_update'),
    path('delete/<int:pk>/', UpdatesDeleteView.as_view(), name='update_delete'),
    path('promote/<int:pk>/', promote_update, name='promote'),
    path('publish/<int:pk>/', updates_publish_view, name='publish_update'),
    path('member/<slug:user>/', UpdatesUserListView.as_view(), name='update_user_list'),
    path('<slug:slug>/', UpdatesDetailView.as_view(), name='update_detail'),
]

qndbacklog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from metrics.models import Currency
from tags.models import MetaDataMixin

# Create your models here.

class Priority(models.Model):

    label = models.CharField(max_length=32, unique=True, blank=True, null=True)
    color = models.CharField(max_length=6, unique=True)
    urgency = models.PositiveIntegerField(default=1)

    class Meta:
      
        ordering = ['urgency',]
        verbose_name = "priority label"
        verbose_name_plural = "priority labels"

    def __str__(self):
          return str(self.label)

class Status(models.Model):

    label = models.CharField(max_length=32, unique=True)

    class Meta:

        verbose_name = "status label"
        verbose_name_plural = "status labels"

    def __str__(self):
        return self.label

class GitBranch(models.Model):

    name = models.CharField(max_length=32, unique=True)
    repo_url = models.CharField(max_length=1024, unique=True)

    class Meta:

        verbose_name = "development branch"
        verbose_name_plural = "development branches"

    def __str__(self):
        return self.name

class Objective(MetaDataMixin, models.Model):

    completion_label = 'COMPLETE'
    commit_label = 'COMMITTED'

    summary = models.TextField(max_length=512)
    target_date = models.DateTimeField(blank=True, null=True)
    completion_date = models.DateTimeField(blank=True, null=True)
    committed = models.BooleanField(default=False)
    bounty_claimed = models.BooleanField(default=False)
    bounty = models.FloatField(blank=True, null=True)
    bounty_unit = models.ForeignKey(Currency, models.SET_NULL, blank=True, null=True)
    assigned_to = models.ForeignKey(
        User,
        models.SET_NULL,
        related_name='assigned_to',
        blank=True,
        null=True,
    )
    status = models.ForeignKey(Status, models.SET_NULL, blank=True, null=True)
    priority = models.ForeignKey(Priority, models.SET_NULL, blank=True, null=True)
    git_branch = models.ForeignKey(GitBranch, models.SET_NULL, blank=True, null=True)

    
    class Meta:

        ordering = ['-priority', 'target_date']
        verbose_name = "Project Objective"
        verbose_name_plural = "project objectives"

    def __str__(self):
        return self.summary

    def mark_complete(instance):
        '''
        Sets the priority and status of an Objective object to indicate
        that it is complete.

        Args:
        
        instance - an instance of an Objective database object
        '''
        priority, created = Priority.objects.get_or_create(
            label=None,
            color='666666',
            urgency=999999,
        )
        status, created = Status.objects.get_or_create(
            label=instance.completion_label
        )
        instance.priority = priority
        instance.status = status
        instance.completion_date = timezone.now()
        instance.save()

    def mark_committed(instance):
        '''
        Sets the commited boolean to True indicating that the Objective has
        been committed and pushed to its Git repository.

        Args:
        
        instance - an instance of an Objective database object
        '''
        if str(instance.status) == Objective.completion_label:
            status, created = Status.objects.get_or_create(
                label=Objective.commit_label
            )
            instance.status = status
            instance.committed = True
            instance.save()

    def mark_bounty_claimed(instance):
        '''
        Sets the bounty_claimed boolean to True indicating that the bounty for 
        completing the Objective has been paid to the assigned user.

        Args:
        
        instance - an instance of an Objective database object
        '''
        if instance.status == Objective.completion_label and instance.committed == True:
            instance.committed = True
            instance.save()

qndbacklog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from .models import Objective, Status, Priority, GitBranch

# Create your views here.


class ObjectiveCreateView(LoginRequiredMixin, CreateView):

    model = Objective
    fields = [
        'summary',
        'assigned_to',
        'priority',
        'target_date',
        'status',
        'git_branch',
    ]
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('backlog:objective_list')

class ObjectiveDetailView(LoginRequiredMixin, DetailView):

    model = Objective
    
class CurrentObjectiveListView(LoginRequiredMixin, ListView):

    model = Objective
    queryset = Objective.objects.filter(committed=False)

class ObjectiveUpdateView(LoginRequiredMixin, UpdateView):

    model = Objective
    fields = [
        'summary',
        'assigned_to',
        'priority',
        'target_date',
        'status',
        'git_branch',
    ]
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('backlog:objective_list')

class ObjectiveDeleteView(LoginRequiredMixin, DeleteView):

    model = Objective
    success_url = reverse_lazy('backlog:backlog_list')

def complete_objective(request, pk):
    o = get_object_or_404(Objective, pk=pk)
    Objective.mark_complete(o)
    return HttpResponseRedirect(reverse('backlog:objective_list'))

def commit_objective(request, pk):
    o = get_object_or_404(Objective, pk=pk)
    Objective.mark_committed(o)
    return HttpResponseRedirect(reverse('backlog:objective_list'))

def pay_bounty(request, pk):
    o = get_object_or_404(Objective, pk=pk)
    Objective.mark_bounty_claimed(o)
    return HttpResponseRedirect(reverse('backlog:objective_list'))

qndbacklog/templates/qndbacklog/objective_create_form.html
{% extends './qnd_base.html' %}
{% block body_block %}
  <div class ="container">
    <h2>New Objective</h2>
    <br>
    <div class="container">
      <form  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add" class="btn btn-success">
      </form>
      <br>
    </div>
  </div>
{% endblock %}

qndbacklog/templates/qndbacklog/objective_list.html
{% extends './qnd_base.html' %}
{% block body_block %}
<div class="container-fluid qnd-bg">
  {% if object_list %}
    {% include "page_control.html" %}
    {% for objective in object_list %}
      {% include "./objective_list_item.html" %}
    {% endfor %}
    {% include "page_control.html" %}
  {% else %}
    <p>There are no objectives to complete! Have a beer!</p>
  {% endif %}
</div>
{% endblock %}

qndbacklog/templates/qndbacklog/objective_list_item.html
<div class="qnd-objective-card float-left" style="border-style: solid; border-color: #{{ objective.priority.color }};">
  {% if objective.priority.label != "None" %}
    <div class="row" style="color: black; background-color: #{{ objective.priority.color}};">
      <div class="col-">
        Priority:
      </div>
      <div class="col">
        <span style="color: black; backgorund-color: white;">{{ objective.priority.label }}</span>
      </div>
    </div>
  {% endif %}
  <div class="row">
    <div class="col-">
      Added:
    </div>
    <div class="col">
      <p>{{ objective.creation_date }}</p>
    </div>
  </div>
  <div class="row">
    <div class="col qnd-objective-summary">
      <p>{{ objective.summary }}</p>
    </div>
  </div>
  <div class="row">
    <div class="col-">
      Assigned to:
    </div>
    <div class="col">
      <p>{% if objective.assigned_to %}{{ objective.assigned_to }}{% else %}Unassigned{% endif %}</p>
    </div>
  </div>
  <div class="row">
    <div class="col-">
      Status:
    </div>
    <div class="col">
      <p>{{ objective.status }}</p>
    </div>
  </div>
  {% if objective.target_date %}
    <div class="row">
      <div class="col-">
        Target:
      </div>
      <div class="col">
        <p>{{ objective.target_date }}</p>
      </div>
    </div>
  {% endif %}
  {% if objective.git_branch %}
    <div class="row">
      <div class="col-">
        Git branch:
      </div>
      <div class="col">
        <p>{{ objective.git_branch }}</p>
      </div>
    </div>
  {% endif %}
  {% if objective.bounty %}
    <div class="row">
      <div class="col-">
        Bounty:
      </div>
      <div class="col">
        <p>{{objective.bounty_unit }}{{ objective.bounty }}</p>
      </div>
    </div>
  {% endif %}
  {% if request.user.is_superuser %}
      <a href="{% url 'backlog:objective_update' objective.pk %}">
        <button class="btn-small btn-warning">Edit</button>
      </a>
  {% endif %}
  {% if objective.completion_date %}
    <div class="row">
      <div class="col-">
        Completed on:
      </div>
      <div class="col">
        <p>{{ objective.completion_date }}</p>
      </div>
    </div>
    {% elif objective.assigned_to == request.user %}
      <a href="{% url 'backlog:complete_objective' objective.pk %}">
        <button class="btn-small btn-primary">&#x2713; Complete</button>
      </a>
    {% endif %}
    {% if objective.completion_date and not committed and objective.assigned_to == request.user %}
      <a href="{% url 'backlog:commit_objective' objective.pk %}">
        <button class="btn-small btn-success">&#x2713; Committed</button>
      </a>
    {% endif %}
  </div>
</div>

qndbacklog/templates/qndbacklog/objective_navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <a class="nav-item navbar-brand" href="/">kbruder.info</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- NAVBAR -->
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
        <span class="navbar-brand qnd-logo">QnD:backlog</span>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'backlog:objective_create' %}">
            <button class="btn btn-sm btn-primary">New Objective</button>
          </a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'updates:update_list' %}">Updates</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'images:gallery_list' %}">Gallery</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'images:piece_list' %}">Artwork</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'people:artist_list' %}">Artists</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>
<br>

qndbacklog/templates/qndbacklog/objective_update_form.html
{% extends './qnd_base.html' %}
{% block body_block %}
  <div class ="container">
    <h2>Edit Objective</h2>
    <br>
    <div class="container">
      <form  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add" class="btn btn-success">
      </form>
      <br>
    </div>
  </div>
{% endblock %}

qndbacklog/templates/qndbacklog/qnd_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>QnD Backlog</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Mono|Permanent+Marker&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Tajawal&display=swap" rel="stylesheet">
 <!-- <link href="https://fonts.googleapis.com/css?family=Ibarra+Real+Nova&display=swap" rel="stylesheet"> -->
  <link href="https://fonts.googleapis.com/css?family=Yeseva+One&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Zilla+Slab+Highlight&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/static/style.css">
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

</head>

<body class="base-bg base-body">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="/static/js/widgets.js"></script>
  {% include './objective_navbar.html' %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
  {% block body_block %}
  <!-- Anything outside of this will be inhereited if you extend! -->
  {% endblock %}
  <!-- FOOTER -->
  <footer class="page-footer font-small base-footer">© kbruder Tech 2020 | <a href="https://www.github.com/kylebruder">My Git Hub</a></footer>
</body>
</html>