images/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from .views import (ImageCreateView, ImageListView, ImageDetailView,
    ImageUpdateView, ImageDeleteView, GalleryCreateView, GalleryListView,
    GalleryDetailView, GalleryUpdateView, GalleryDeleteView, PieceCreateView,
    PieceListView, PieceDetailView, PieceUpdateView, PieceDeleteView,
    promote_gallery, promote_piece, ImageUserListView, GalleryUserListView,
    PieceUserListView, publish_image_view, publish_gallery_view,
    publish_piece_view,)

app_name = "images"

urlpatterns = [
    path(
        'upload/',
        ImageCreateView.as_view(),
        name='image_create'
    ),
    path(
        '',
        ImageListView.as_view(),
        name='image_list'
    ),
    
    path(
        '<int:pk>/',
        ImageDetailView.as_view(),
        name='image_detail'
    ),
    path(
        'modify/<int:pk>/',
        ImageUpdateView.as_view(),
        name='image_update'
    ),
    path('publish/<int:pk>/', publish_image_view, name='publish_image'),
    path('artwork/publish/<slug:slug>/', publish_piece_view, name='publish_piece'),
    path(
        'gallery/create/',
        GalleryCreateView.as_view(),
        name='gallery_create'
    ),
    path(
        'gallery/',
        GalleryListView.as_view(),
        name='gallery_list'
    ),
    path(
        'gallery/<slug:slug>/',
        GalleryDetailView.as_view(),
        name='gallery_detail'
    ),
    path(
        'gallery/modify/<slug:slug>/',
        GalleryUpdateView.as_view(),
        name='gallery_update'
    ),
    path(
        'gallery/delete/<int:pk>/',
        GalleryDeleteView.as_view(),
        name='gallery_delete'
    ),
    path(
        'gallery/promote/<int:pk>/',
        promote_gallery,
        name='promote_gallery'
    ),
    path('gallery/publish/<slug:slug>/', publish_gallery_view, name='publish_gallery'),
    path(
        'artworks/add/',
        PieceCreateView.as_view(),
        name='piece_create'
    ),
    path(
        'artworks/modify/<slug:slug>/',
        PieceUpdateView.as_view(),
        name='piece_update'
    ),
    path(
        'artworks/',
        PieceListView.as_view(),
        name='piece_list'
    ),
    path(
        'artworks/<slug:slug>/',
        PieceDetailView.as_view(),
        name='piece_detail'
    ),
    path(
        'artworks/delete/<int:pk>/',
        PieceDeleteView.as_view(),
        name='piece_delete'
    ),
    path(
        'artworks/promote/<int:pk>/',
        promote_piece,
        name='promote_piece'
    ),
    path(
        'member/<slug:user>/',
        ImageUserListView.as_view(),
        name='image_user_list'
    ),
    path(
        'gallery/member/<slug:user>/',
        GalleryUserListView.as_view(),
        name='gallery_user_list'
    ),
    path(
        'artworks/member/<slug:user>/',
        PieceUserListView.as_view(),
        name='piece_user_list'
    ),
]

links/urls.py
from django.urls import path
from .views import (LinkCreateView, LinkListView, LinkDetailView,
    LinkUpdateView, LinkDeleteView, LinkUserListView, promote_link,
    publish_link_view)

app_name = "links"

urlpatterns = [
    path('add/', LinkCreateView.as_view(), name='link_create'),
    path('', LinkListView.as_view(), name='link_list'),
    path('<int:pk>/', LinkDetailView.as_view(), name='link_detail'),
    path('modify/<int:pk>/', LinkUpdateView.as_view(), name='link_update'),
    path('delete/<int:pk>/', LinkDeleteView.as_view(), name='link_delete'),
    path('promote/<int:pk>/', promote_link, name='promote'),
    path('publish/<int:pk>/', publish_link_view, name='publish_link'),
    path('member/<slug:user>/', LinkUserListView.as_view(), name='link_user_list')
]
 

people/urls.py
from django.urls import path
from people.views import (ArtistCreateView, ArtistListView, ArtistDetailView,
    ArtistUpdateView, ArtistDeleteView, ArtistUserListView, publish_artist_view, 
    promote_artist)

app_name = "people"

urlpatterns = [
    path('artists/new/', ArtistCreateView.as_view(), name="artist_create"),
    path('artists/modify/<slug:slug>/', ArtistUpdateView.as_view(), name="artist_update"),
    path('artists/delete/<int:pk>/', ArtistDeleteView.as_view(), name="artist_delete"),
    path('artists/publish/<slug:slug>/', publish_artist_view, name="artist_publish"),
    path('artists/promote/<int:pk>/', promote_artist, name="artist_promote"),
    path('artists/member/<slug:user>/', ArtistUserListView.as_view(), name="artist_user_list"),
    path('artists/<slug:slug>/', ArtistDetailView.as_view(), name="artist_detail"),
    path('artists/', ArtistListView.as_view(), name="artist_list"),
]

tags/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from tags.views import TagCreateView

app_name = "tags"

urlpatterns = [
    path('new/', TagCreateView.as_view(), name='new'),
]

updates/urls.py
#from django.contrib import admin
from django.urls import path
from .views import (
    UpdatesListView, UpdatesDetailView, UpdatesCreateView,
    UpdatesUpdateView, UpdatesDeleteView, promote_update,
    UpdatesUserListView, updates_publish_view,
)

app_name = 'updates'
urlpatterns = [
    path('', UpdatesListView.as_view(), name='update_list'),
    path('add/', UpdatesCreateView.as_view(), name='update_create'),
    path('modify/<slug:slug>/', UpdatesUpdateView.as_view(), name='update_update'),
    path('delete/<int:pk>/', UpdatesDeleteView.as_view(), name='update_delete'),
    path('promote/<int:pk>/', promote_update, name='promote'),
    path('publish/<int:pk>/', updates_publish_view, name='publish_update'),
    path('member/<slug:user>/', UpdatesUserListView.as_view(), name='update_user_list'),
    path('<slug:slug>/', UpdatesDetailView.as_view(), name='update_detail'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>kbruder Tech</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">  
  <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Mono|Permanent+Marker&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Tajawal&display=swap" rel="stylesheet">
 <!-- <link href="https://fonts.googleapis.com/css?family=Ibarra+Real+Nova&display=swap" rel="stylesheet"> --> 
  <link href="https://fonts.googleapis.com/css?family=Yeseva+One&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Zilla+Slab+Highlight&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/static/style.css">
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

</head>

<body class="base-bg base-body">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="/static/js/widgets.js"></script>
  {% include './base_navbar.html' %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
  {% block body_block %}
  <!-- Anything outside of this will be inhereited if you extend! -->
  {% endblock %}
  <!-- FOOTER -->
  <footer class="page-footer font-small base-footer">© kbruder Tech 2020 | <a href="https://www.github.com/kylebruder">My Git Hub</a></footer>
</body>
</html>

templates/base_navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <a class="nav-item navbar-brand" href="/">kbruder.info</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- NAVBAR -->
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'updates:update_list' %}">Updates</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'images:gallery_list' %}">Gallery</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'images:piece_list' %}">Artwork</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'people:artist_list' %}">Artists</a>
        </li>
      </ul>
      <div class="btn-group">
          {% include "./base_nav_user_dropdown.html" %}
          {% include "./base_nav_add_dropdown.html" %}
      </div>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'updates:update_list' %}">Updates</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'images:gallery_list' %}">Gallery</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'images:piece_list' %}">Artwork</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'people:artist_list' %}">Artists</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<div class="container index-bg">
  <!-- ROW 1 -->
  <div class="row">
    {% if update %}
      <div class="col-md">
        {% include "index_update.html" %}
      </div>
    {% endif %}
  </div>
  <!-- ROW 3 -->
  <div class="row">
    {% if updates %}
      <div class="col-md">
        {% include "index_updates.html" %}
      </div>
    {% endif %}
  </div>
  <!-- ROW 2 -->
  <div class="row">
    {% if gallery %}
      <div class="col-sm">
          {% include "index_gallery.html" %}
      </div>
    {% endif %}
    {% if artist %}
      <div class="col-sm">
          {% include "index_artists.html" %}
      </div>
    {% endif %}
    {% if piece %}
      <div class="col-sm">
          {% include "index_pieces.html" %}
      </div>
    {% endif %}
  </div>
  <!-- ROW 4 -->
  <div class="row">
    {% if links %}
      <div class="col-sm">
        {% include "index_links.html" %}
      </div>
    {% endif %}
  </div>
  <!-- ROW 5 -->
  <div class="row">
    <div class="col">
        {% include "index_kbtech.html" %}
    </div>
  </div>
</div>
{% endblock %}

templates/index_artists.html
<h3 class="people-artist-title">Artists</h3>
<a href="{% url 'people:artist_detail' artist.slug %}" class="">
  <h4 class="people-artist-caption">{{ artist.name }}</h4>
</a>
<img src="{{ artist.image.thumbnail_file.url }}" class="index-artist-thumbnail float-left" alt="{{ artist.image.caption }}">
<p class="people-artist-caption">"{{ artist.statement }}"</p>
<div class="clear"></div>
<br>
{% if artists %}
{% for a in artists%}
  <a href="{% url 'people:artist_detail' a.slug %}">
    <div class="studio-images-card float-left" style="background-image:url('/media/{{ a.image.thumbnail_file }}')">
    </div>
  </a>
{% endfor %}
<div class="clear"></div>
<p>
  <a href="{% url 'people:artist_list' %}">more ...</a>
</p>
{% endif %}

templates/index_gallery_link.html
<div class="row">
  <div class="col-10">
    <img src="/media/{{ link.image.thumbnail_file }}" class="updates-link-image float-left">
    <a href="{{ link.url }}" class="updates-link">
      <h5 class="updates-link-title">{{ link.title }}</h5>
    </a>
    <p class="links-list-description">{{ link.description }}</p>
  </div>
</div>
<br>
<!-- ROW 2 -->
<div class="row">
  <div class="col-10">
    <p class="updates-link">{{ link.url }}</p>
  </div>
</div>

templates/index_image.html
<div class="container index-image-bg">
  <h3 class="index-image-title">Featured Image</h3>
  <h5 class="index-image-title">
    <a href="{% url 'images:image_detail' image.pk %}">{{ image.title}}</a>
  </h5>
  <img src="{{ image.thumbnail_file.url }}" class="index-image float-left" alt="{{ image.title }}">
  <p class="index-image-caption">{{ image.caption }}</p>
  <p class="index-image-credit clear">{{ image.credit }}</p>
  <p class="clear">
    <a href="{% url 'images:image_list' %}">
      more images
    </a>
  </p>
</div>

templates/index_kbtech.html
<div class="kbtech-title">
  <div class="row">
    <div class="col">
      <h1>kbruder Tech</h1>
      <h2 class="kbtech-subtitle">Information Technology Consulting</h2>
      <p class="kbtech-services-overview">Cloud | IP networking | Infrastructure | Deployment | Cryptocurrency | Info Sec</p>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <p class="kbtech-services">Providing consultation and support to individuals and businesses requiring modern, secure, and cost-reducing IT solutions. Offering solution architecture, Information Security services and general information about emerging trends in Information Technology.</p>
      <p class="kbtech-services">The biggest hurdle in IT services is trust. Begin a trust relationship with kbruder Tech. Send me a concise email message to <a href="mailto:help@kbruder.info">help@kbruder.info</a> today!</p>
    </div>
  </div>
</div>

templates/index_pieces.html
<h3 class="index-image-title">Art/Photo</h3>
<a href="{% url 'images:piece_detail' piece.slug %}">
  <h5 class="index-gallery-caption">{{ piece.image.title }}</h5>
</a>
<img src="{{ piece.image.thumbnail_file.url }}" class="index-gallery-thumbnail float-left" alt="{{ piece.image.title }}">
<p class="index-gallery-caption">{{ piece.description }}</p>
<div class="clear"></div>
<br>
{% if pieces %}
  {% for p in pieces %}
    <a href="{% url 'images:piece_detail' p.slug %}">
      <div class="studio-images-card float-left" style="background-image:url('/media/{{ p.image.thumbnail_file }}')">
      </div>
    </a>
  {% endfor %}
  <div class="clear"></div>
  <p>
    <a href="{% url 'images:piece_list' %}">more ...</a>
  </p>
{% endif %}

templates/index_update.html
<div class="container index-update-bg">
  <a href="{% url 'updates:update_detail' slug=update.slug %}">
    <div class="jumbotron index-headline-text" style="background-image:url('/media/{{ update.headline_img.image_file }}')">
      <h1>{{ update.headline }}</h1>
    </div>
  </a>
</div>

templates/studio.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container-fluid studio-bg">
  <div class="row">
    <div class="col-sm">
      {% include './studio_updates.html' %}
    </div>
    <div class="col-sm">
      {% include './studio_galleries.html' %} 
    </div>
    <div class="col-sm">
      {% include './studio_artists.html' %} 
    </div>
    <div class="col-sm">
      {% include './studio_pieces.html' %}
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      {% include './studio_links.html' %}
    </div>
    <div class="col-sm-4">
      {% include './studio_images.html' %}
    </div>
  </div>
</div>
{% endblock %}

templates/studio_artists.html
<h4 class="studio-gallery-title">Your Artists</h4>
<a href="{% url 'people:artist_create' %}?next={{ request.path }}">
  <button class="btn-sm btn-primary">New</button>
</a>
{% if artists %}
  {% for a in artists %}
    <ul class="list-group">
      <li class="list-group-item studio-gallery-li">
        {% if a.image %}
          <img class="studio-gallery-thumbnail float-right" src="{{ a.image.thumbnail_file.url }}" alt="{{ a.image.caption }}">
        {% endif %}
        <h5 class="">
          <a href="{% url 'people:artist_detail' a.slug %}">
            {{ a.name }}
          </a>
        </h5>
        <p class="studio-gallery-status">
          Created: {{ a.creation_date|date:"M d, Y" }}
        </p>
        {% if not a.is_public %}
          <span class="badge badge-secondary">Unpublished</span>
        {% endif %}
        <a href="{% url 'people:artist_update' a.slug %}?next={{ request.path }}">
          <button class="btn-sm btn-warning"><span class="studio-button-text">&#x1F589;</span></button>
        </a>
        {% if not a.is_public %}
          <a href="{% url 'people:artist_delete' a.pk %}">
            <button class="btn-sm btn-danger"><span class="studio-button-text">&#x2715;</span></button>
          </a>
        {% endif %}
        <div class="clear"></div>
    </li>
  {% endfor %}
  <p>
    <a href="{% url 'people:artist_user_list' user %}">more ...</a>
  </p>
{% else %}
  <p>You have not profiled any artist yet</p>
  <a href="{% url 'people:artist_create' %}">
    <button class="btn btn-success">New Artist</button>
  </a>
{% endif %}
<br>
<br>

templates/studio_galleries.html
<h4 class="studio-gallery-title">Your Galleries</h4>
  <a href="{% url 'images:gallery_create' %}?next={{ request.path }}">
    <button class="btn-sm btn-primary">New</button>
  </a>
{% if galleries %}
  {% for g in galleries %}
    <ul class="list-group">
      <li class="list-group-item studio-gallery-li">
        {% if g.cover_image %}
          <img class="studio-gallery-thumbnail float-right" src="{{ g.cover_image.thumbnail_file.url }}" alt="{{ g.cover_image.caption }}">
        {% endif %}
        <h5 class="">
          <a href="{% url 'images:gallery_detail' g.slug %}">
            {{ g.title }}
          </a>
        </h5>
        <p class="studio-gallery-status">
          Created: {{ g.creation_date|date:"M d, Y" }}
        </p>
        {% if not g.is_public %}
          <span class="badge badge-secondary">Unpublished</span>
        {% endif %}
        <a href="{% url 'images:gallery_update' g.slug %}?next={{ request.path }}">
          <button class="btn-sm btn-warning"><span class="studio-button-text">&#x1F589;</span></button>
        </a>
        {% if not g.is_public %}
          <a href="{% url 'images:gallery_delete' g.pk %}?next={{ request.path }}">
            <button class="btn-sm btn-danger"><span class="studio-button-text"> &#x2715; </span></button>
          </a>
        {% endif %}
        <div class="clear"></div>
    </li>
  {% endfor %}
  <p>
    <a href="{% url 'images:gallery_user_list' request.user %}">more ...</a>
  </p>
{% else %}
  <p>You have not contributed any galleries yet</p>
  <a href="{% url 'images:gallery_create' %}">
    <button class="btn btn-success">New Gallery</button>
  </a>
{% endif %}

templates/studio_images.html
<h4 class="studio-image-title">Your Images</h4>
{% if images %}
  {% for i in images %}
    <a href="{% url 'images:image_detail' i.pk %}">
      <div class="studio-images-card float-left" style="background-image:url('/media/{{ i.thumbnail_file }}')">
        {% if not i.is_public %}
          <span class="badge badge-secondary">Unpublished</span>
        {% endif %}
      </div>
    </a>
  {% endfor %}
  <div class="clear"></div>
  <p>
    <a href="{% url 'images:image_user_list' user=user %}">more ...</a>
  </p>
{% else %}
  <p>You have not contributed any images yet</p>
  <a href="{% url 'images:image_create' %}">
    <button class="btn btn-success">New Image</button>
  </a>
{% endif %}

templates/studio_navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <a class="nav-item navbar-brand" href="/">kbruder.info</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- NAVBAR -->
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'updates:update_user_list' user %}">Your Updates</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'images:gallery_user_list' user %}">Your Galleries</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'people:artist_user_list' user %}">Your Artists</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'images:piece_user_list' user %}">Your Artwork</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'links:link_user_list' user %}">Your Links</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'images:image_user_list' user %}">Your Images</a>
        </li>
    </ul>
  </div>
</nav>